// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: core/endorser/sharding/protos/shard.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShardCommunication_Step_FullMethodName = "/protos.ShardCommunication/Step"
)

// ShardCommunicationClient is the client API for ShardCommunication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardCommunicationClient interface {
	// Step passes a Raft message to the recipient node
	Step(ctx context.Context, in *RaftMessageProto, opts ...grpc.CallOption) (*StepResponse, error)
}

type shardCommunicationClient struct {
	cc grpc.ClientConnInterface
}

func NewShardCommunicationClient(cc grpc.ClientConnInterface) ShardCommunicationClient {
	return &shardCommunicationClient{cc}
}

func (c *shardCommunicationClient) Step(ctx context.Context, in *RaftMessageProto, opts ...grpc.CallOption) (*StepResponse, error) {
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, ShardCommunication_Step_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardCommunicationServer is the server API for ShardCommunication service.
// All implementations must embed UnimplementedShardCommunicationServer
// for forward compatibility
type ShardCommunicationServer interface {
	// Step passes a Raft message to the recipient node
	Step(context.Context, *RaftMessageProto) (*StepResponse, error)
	mustEmbedUnimplementedShardCommunicationServer()
}

// UnimplementedShardCommunicationServer must be embedded to have forward compatible implementations.
type UnimplementedShardCommunicationServer struct {
}

func (UnimplementedShardCommunicationServer) Step(context.Context, *RaftMessageProto) (*StepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedShardCommunicationServer) mustEmbedUnimplementedShardCommunicationServer() {}

// UnsafeShardCommunicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardCommunicationServer will
// result in compilation errors.
type UnsafeShardCommunicationServer interface {
	mustEmbedUnimplementedShardCommunicationServer()
}

func RegisterShardCommunicationServer(s grpc.ServiceRegistrar, srv ShardCommunicationServer) {
	s.RegisterService(&ShardCommunication_ServiceDesc, srv)
}

func _ShardCommunication_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftMessageProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardCommunicationServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardCommunication_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardCommunicationServer).Step(ctx, req.(*RaftMessageProto))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardCommunication_ServiceDesc is the grpc.ServiceDesc for ShardCommunication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardCommunication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ShardCommunication",
	HandlerType: (*ShardCommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Step",
			Handler:    _ShardCommunication_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/endorser/sharding/protos/shard.proto",
}
