// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: core/endorser/sharding/protos/shard.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RaftMessageProto wraps a serialized raftpb.Message
type RaftMessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageProto) Reset() {
	*x = RaftMessageProto{}
	mi := &file_core_endorser_sharding_protos_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageProto) ProtoMessage() {}

func (x *RaftMessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_endorser_sharding_protos_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageProto.ProtoReflect.Descriptor instead.
func (*RaftMessageProto) Descriptor() ([]byte, []int) {
	return file_core_endorser_sharding_protos_shard_proto_rawDescGZIP(), []int{0}
}

func (x *RaftMessageProto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_core_endorser_sharding_protos_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_endorser_sharding_protos_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_core_endorser_sharding_protos_shard_proto_rawDescGZIP(), []int{1}
}

func (x *StepResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StepResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_core_endorser_sharding_protos_shard_proto protoreflect.FileDescriptor

const file_core_endorser_sharding_protos_shard_proto_rawDesc = "" +
	"\n" +
	")core/endorser/sharding/protos/shard.proto\x12\x06protos\"&\n" +
	"\x10RaftMessageProto\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\">\n" +
	"\fStepResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2N\n" +
	"\x12ShardCommunication\x128\n" +
	"\x04Step\x12\x18.protos.RaftMessageProto\x1a\x14.protos.StepResponse\"\x00B=Z;github.com/hyperledger/fabric/core/endorser/sharding/protosb\x06proto3"

var (
	file_core_endorser_sharding_protos_shard_proto_rawDescOnce sync.Once
	file_core_endorser_sharding_protos_shard_proto_rawDescData []byte
)

func file_core_endorser_sharding_protos_shard_proto_rawDescGZIP() []byte {
	file_core_endorser_sharding_protos_shard_proto_rawDescOnce.Do(func() {
		file_core_endorser_sharding_protos_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_endorser_sharding_protos_shard_proto_rawDesc), len(file_core_endorser_sharding_protos_shard_proto_rawDesc)))
	})
	return file_core_endorser_sharding_protos_shard_proto_rawDescData
}

var file_core_endorser_sharding_protos_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_endorser_sharding_protos_shard_proto_goTypes = []any{
	(*RaftMessageProto)(nil), // 0: protos.RaftMessageProto
	(*StepResponse)(nil),     // 1: protos.StepResponse
}
var file_core_endorser_sharding_protos_shard_proto_depIdxs = []int32{
	0, // 0: protos.ShardCommunication.Step:input_type -> protos.RaftMessageProto
	1, // 1: protos.ShardCommunication.Step:output_type -> protos.StepResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_endorser_sharding_protos_shard_proto_init() }
func file_core_endorser_sharding_protos_shard_proto_init() {
	if File_core_endorser_sharding_protos_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_endorser_sharding_protos_shard_proto_rawDesc), len(file_core_endorser_sharding_protos_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_endorser_sharding_protos_shard_proto_goTypes,
		DependencyIndexes: file_core_endorser_sharding_protos_shard_proto_depIdxs,
		MessageInfos:      file_core_endorser_sharding_protos_shard_proto_msgTypes,
	}.Build()
	File_core_endorser_sharding_protos_shard_proto = out.File
	file_core_endorser_sharding_protos_shard_proto_goTypes = nil
	file_core_endorser_sharding_protos_shard_proto_depIdxs = nil
}
